{
  imports = [
    ./oh-my-posh
    ./pi
    ./tmux

    ./anki.nix
    ./appimage.nix
    ./bat.nix
    ./bitwarden.nix
    ./btop.nix
    ./calendar.nix
    ./delta.nix
    ./difftastic.nix
    ./direnv.nix
    ./discord.nix
    ./element.nix
    ./espanso.nix
    ./eza.nix
    ./fastfetch.nix
    ./feh.nix
    ./ffmpeg.nix
    ./fzf.nix
    ./gh.nix
    ./ghostty.nix
    ./git.nix
    ./gpu-screen-recorder.nix
    ./gpg.nix
    ./handy.nix
    ./helium.nix
    ./hyperfine.nix
    ./imagemagick.nix
    ./jj.nix
    ./lightpanda.nix
    ./localsend.nix
    ./mpv.nix
    ./nh.nix
    ./nvim.nix
    ./obsidian.nix
    ./perf.nix
    ./plann.nix
    ./poppler-utils.nix
    ./ripgrep.nix
    ./seahorse.nix
    ./sioyek.nix
    ./speedtest.nix
    ./taman.nix
    ./thunderbird.nix
    ./upterm.nix
    ./uxplay.nix
    ./wakatime.nix
    ./wireshark.nix
    ./yazi.nix
    ./yt-dlp.nix
    ./zen.nix
    ./zip.nix
    ./zoxide.nix
  ];
}
