{
  imports = [
    ./helium

    ./appimage.nix
    ./bat.nix
    ./btop.nix
    ./direnv.nix
    ./eza.nix
    ./fastfetch.nix
    ./ffmpeg.nix
    ./fzf.nix
    ./gpg.nix
    ./herdr.nix
    ./hyperfine.nix
    ./imagemagick.nix
    ./localsend.nix
    ./mpv.nix
    ./obsidian.nix
    ./perf.nix
    ./poppler-utils.nix
    ./ripgrep.nix
    ./sioyek.nix
    ./speedtest.nix
    ./thunderbird.nix
    ./uxplay.nix
    ./yazi.nix
    ./yt-dlp.nix
    ./zip.nix
    ./zoxide.nix
  ];
}
