{
  config,
  lib,
  pkgs,
  atlas,
  ...
}:

let
  inherit (config) planet;
  inherit (planet.programs) thunderbird;
in
{
  options.planet.programs.thunderbird.enable = lib.mkOption {
    type = lib.types.bool;
    default = planet.desktop.enable;
    description = "Enable the Thunderbird mail client.";
  };

  config = lib.mkIf thunderbird.enable {
    programs.thunderbird = {
      enable = true;
      package = pkgs.thunderbird-bin;
    };

    hjem.users = atlas.travellers.forEach planet (_: {
      files = {
        ".thunderbird/profiles.ini".text = lib.generators.toINI { } {
          General = {
            StartWithLastProfile = 1;
            Version = 2;
          };

          Profile0 = {
            Name = "default";
            Path = "default";
            IsRelative = 1;
            Default = 1;
          };
        };
        ".thunderbird/default/user.js".text = ''
          // Generated by unixverse.

          user_pref("mail.openpgp.allow_external_gnupg", false);
        '';
      };
    });
  };
}
