steps:
  check:
    image: nixos/nix
    environment:
      BINARY_CACHE: https://cache.lukasl.dev/universe
      BINARY_CACHE_PUBLIC_KEY: universe:w0jdMOE2LZ74t2WSja4jKaMBPzai2aVM/VuBzszi0BQ=
      BINARY_CACHE_ACCESS_TOKEN:
        from_secret: binary_cache_access_token
    commands:
      - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - echo "extra-substituters = $BINARY_CACHE" >> /etc/nix/nix.conf
      - echo "extra-trusted-public-keys = $BINARY_CACHE_PUBLIC_KEY" >> /etc/nix/nix.conf
      - echo "machine cache.lukasl.dev password $BINARY_CACHE_ACCESS_TOKEN" > ~/.netrc
      - export NIX_CONFIG="netrc-file = $HOME/.netrc"
      # - nix run nixpkgs#attic-client -- login attic $BINARY_CACHE $BINARY_CACHE_ACCESS_TOKEN
      - nix flake check

when:
  - event: [push, pull_request]
