steps:
  check:
    image: nixos/nix
    environment:
      BINARY_CACHE: https://cache.lukasl.dev/universe
      BINARY_CACHE_PUBLIC_KEY: universe:w0jdMOE2LZ74t2WSja4jKaMBPzai2aVM/VuBzszi0BQ=
      BINARY_CACHE_ACCESS_TOKEN:
        from_secret: binary_cache_access_token
    commands:
      - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - echo "extra-substituters = $BINARY_CACHE" >> /etc/nix/nix.conf
      - echo "extra-trusted-public-keys = $BINARY_CACHE_PUBLIC_KEY" >> /etc/nix/nix.conf
      - echo "machine cache.lukasl.dev password $BINARY_CACHE_ACCESS_TOKEN" > /etc/nix/netrc
      - export NIX_CONFIG="netrc-file = /etc/nix/netrc"
      - |
        if [ "$(uname -m)" = "x86_64" ]; then
          nix eval --raw .#nixosConfigurations.orion.config.system.build.toplevel.drvPath
          nix eval --raw .#nixosConfigurations.vega.config.system.build.toplevel.drvPath
          nix eval --raw .#nixosConfigurations.pollux.config.system.build.toplevel.drvPath
          nix eval --raw .#vim.drvPath
        fi
      - |
        if [ "$(uname -m)" = "aarch64" ]; then
          nix eval --raw .#nixosConfigurations.ida.config.system.build.toplevel.drvPath
          nix eval --raw .#vim.drvPath
        fi

when:
  - event: [push, pull_request]
