steps:
  build:
    image: voidcontext/woodpecker-plugin-nix-attic:0.2.0
    settings:
      binary_cache: https://cache.lukasl.dev/universe
      binary_cache_public_key: universe:w0jdMOE2LZ74t2WSja4jKaMBPzai2aVM/VuBzszi0BQ=
      binary_cache_token:
        from_secret: binary_cache_access_token
      script: |
        attic login attic $PLUGIN_BINARY_CACHE $PLUGIN_BINARY_CACHE_TOKEN
        echo "machine cache.lukasl.dev password $PLUGIN_BINARY_CACHE_TOKEN" > ~/.netrc
        export NIX_CONFIG="netrc-file = $HOME/.netrc"

        nix flake check

when:
  - event: [push, pull_request]
