steps:
  build:
    image: voidcontext/woodpecker-plugin-nix-attic:0.2.0
    settings:
      binary_cache: https://cache.lukasl.dev/vega
      binary_cache_public_key: vega:B57uOXZgdBLi/6kEAnfmoIpIg+V8/RjLvxQI6iVCtO8=
      binary_cache_token:
        from_secret: vega_binary_cache_access_token
      script: |
        attic login attic $PLUGIN_BINARY_CACHE $PLUGIN_BINARY_CACHE_TOKEN

        echo "machine cache.lukasl.dev password $PLUGIN_BINARY_CACHE_TOKEN" > ~/.netrc

        export NIX_CONFIG="netrc-file = $HOME/.netrc"

        nix build \
          --substituters "https://cache.nixos.org $PLUGIN_BINARY_CACHE" \
          --trusted-public-keys "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= $PLUGIN_BINARY_CACHE_PUBLIC_KEY" \
          .#nixosConfigurations.vega.config.system.build.toplevel

        attic push attic:vega $(nix path-info .#nixosConfigurations.vega.config.system.build.toplevel)

when:
  - event: [push, pull_request]
    path:
      - ".woodpecker/vega.yaml"
      - "planets/vega/**"
      - "options/**"
      - "packages/**"
      - "flake.nix"
      - "flake.lock"
