name: Deadnix

on:
  push:
    branches: [ master, main]
    paths: [ "**.nix" ]
  pull_request:
    branches: [ master, main ]
    paths: [ "**.nix" ]

jobs:
  deadcode:
    name: Dead code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
