name: DNS

on:
  push:
    branches: [ master, main ]
    paths: [ "dns/**" ]

jobs:
  push-dns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dnscontrol
        uses: gacts/install-dnscontrol@v1
        with:
          version: latest

      - name: Push DNS Changes
        env:
          CLOUDFLARE_API_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_API_ACCOUNT_ID }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_API_USER: ${{ secrets.CLOUDFLARE_API_USER }}
        run: dnscontrol push --config ./dns/dnsconfig.js --creds ./dns/creds.ci.json
