name: Flake

on:
  push:
    branches: [ master, main]
  pull_request:
    branches: [ master, main ]

jobs:
  flake-check:
    name: Flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable QEMU for cross-arch builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            extra-experimental-features = nix-command flakes
            extra-platforms = aarch64-linux
      - name: Run Nix Flake Check
        run: nix flake check
