on:
  push:
    branches: [ master, main]
  pull_request:
    branches: [ master, main ]

name: Flake check

jobs:
  flake-check:
    name: Check flake 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v25
      - name: Run Nix Flake Check
        run: nix flake check
