name: Flake

on:
  push:
    branches: [ master, main]
  pull_request:
    branches: [ master, main ]

jobs:
  flake-check:
    name: Flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Run Nix Flake Check
        run: nix flake check

