on:
  push:
    branches: [ master, main]
  pull_request:
    branches: [ master, main ]

name: Nix

jobs:
  deadcode:
    name: Dead code analysis
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
  flake-check:
    name: Flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Run Nix Flake Check
        run: nix flake check

